work_dir: /Users/loerfy/opts

rpc-server:
  poolsize: 5
  addr: ral.sock

bolt-path: bbolt

search:
  poolsize: 10
  addr: /tmp/rust-uds.sock

meilisearch:
  host: http://127.0.0.1:7700
  api-key: Jsz678dsHJ67s

google:
  analytics_id: 153425181