postgres:
  user: postgres
  password: sit-fine
  port: 5432
  host: 0.0.0.0
  database: api
  sslmode: disable

redis:
  address: 127.0.0.1:6379
  password: 
  db: 0
  enabled: false

google:
  analytics_id: 153425181
