config_dir = "/Users/loerfy/opts"

log-path = "_logs"

[hitokoto]
dbpath = "bbolt"
source = "hito"

[rate-limit]
poolsize = 5
addr = "ral.sock"
enable = true

[search]
poolsize = 10
addr = "search.sock"

[credential]
analytics-id = "153425181"
filename = "credential.json"
