apiVersion: v1
kind: PersistentVolume
metadata:
    name: postgres-pv
    labels:
        type: local
spec:
    storageClassName: manual
    capacity:
        storage: 100Mi
    accessModes:
    - ReadWriteOnce
    hostPath:
        path: "/Users/wincer/db"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: postgres-pv-claim
    labels:
        app: postgres
spec:
    storageClassName: manual
    resources:
        requests:
            storage: 100Mi
    accessModes:
    - ReadWriteOnce
