apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: redis
spec:
    template:
        metadata:
            name: redis
            labels:
                app: redis
        spec:
            containers:
            - image: loerfy/redis-cell:v1.0
              name: redis
              imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
    name: redis
spec:
    type: LoadBalancer
    selector:
        app: redis
    ports:
    - port: 6379
      targetPort: 6379
