defaults: &defaults
  docker:
    - image: circleci/golang:1.14.2

version: 2

jobs: 
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build
          command: |
            go build -o server
      - save_cache:
          key: hitokoto-v1-{{ checksum "config_sample.json" }}
          paths:
            - server

workflows:
  version: 2

  Hito-CI:
    jobs:
      - build
